services:
  # Landing Page Pública (Subred Pública en AWS)
  frontend_public:
    build: ./frontend-public
    container_name: cybersoc_public_ui
    ports:
      - "80:80"

  # Dashboard Privado (Subred Privada en AWS)
  frontend_private:
    build: ./frontend-private
    container_name: cybersoc_private_ui
    ports:
      - "8080:80"

  # API Backend
  api_backend:
    build: ./backend
    container_name: cybersoc_api
    ports:
      - "5000:5000"
    volumes:
      - ./backend/logs:/app/logs
    depends_on:
      - database
    env_file:
      - .env
  # Base de Datos
  database:
    image: mongo:6.0
    container_name: cybersoc_db
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: